### ISSUE TITLE
Memory leak issue

### ISSUE THREAD

**Issue by kansi** [travelping/exometer_influxdb#40] opened 2017-05-01 14:16 UTC
Hi, I have been using `exometer_infludb` along with my Phoenix app. But I have found that the `exometer_report_influxdb` plugin doesn't release memory. Currently, its consuming more than`300MB` of memory and has around 400K messages in its queue.  My `pool_interval` is 3 seconds. Any pointers on why is it exhibiting this behavour?

**Comment by surik** [comment] 2017-05-02 12:29
Hi,

Can you say version/revision which you use?

**Comment by kansi** [comment] 2017-05-02 17:38
I am using the commit from the master https://github.com/travelping/exometer_influxdb/commit/6aa389b5d36d3b0935ab4f77fb65f96e0dd18286

**Comment by surik** [comment] 2017-05-03 12:24
Without analyze of reporter and InfluxDB configuration, it is hard to say what's the problem. Are you sure that you have any metrics in DB?

**Comment by kansi** [comment] 2017-05-04 06:05
If you suggest me regarding how to analyze this issue then I will try to do the same and debug the problem. I am using default deployment of InfluxDB no change at all. I do get metrics in the db but over a period of time the heap for the influx reporter process keeps growing.

**Comment by mgumz** [comment] 2017-05-04 06:57
@kansi you need to provide sample code of what and how you are using it, how you have setup the exporter, etc. as vague as your current bug-description is, noone will be able to find the root cause of the problem for you.

**Comment by kansi** [comment] 2017-05-04 07:20
The following is my config for elixometer/exometer_core
```
poll_interval    = 3_000
vm_memory        = ~w(erlang memory)a
memory_stats     = ~w(total processes processes_used system ets binary code atom atom_used)a
vm_processes     = ~w(erlang beam process)a
processes_stat   = ~w(process_count process_limit run_queue_size)a
vm_scheduler     = ~w(erlang beam scheduler_usage)a
scheduler_stat   = :lists.seq(1, :erlang.system_info(:schedulers))
vm_gc            = ~w(erlang beam garbage_collection)a
gc_stat          = ~w(number_of_gcs, words_reclaimed)a
vm_io            = ~w(erlang beam io)a
io_stat          = ~w(input output)a
vm_processor     = ~w(erlang beam processor)a
processor_stat   = ~w(logical_processors logical_processors_available logical_processors_online)a
vm_ports         = ~w(erlang beam port)a
ports_stat       = ~w(port_count port_limit)a
vm_uptime        = ~w(erlang beam uptime)a
uptime_stat      = ~w(value)a
vm_statistics    = ~w(erlang statistics)a
beam_stat        = ~w(run_queue)a

config :exometer_core,
  predefined: [
    {vm_memory, {:function, :erlang, :memory, [], :proplist, memory_stats}, []},
    {vm_processes, {:function, Metricman, :process_info, [], :proplist, processes_stat}, []},
    {vm_scheduler, {:function, :recon, :scheduler_usage, [1000], :proplist, scheduler_stat}, []},
    {vm_gc, {:function, Metricman, :garbage_collection, [], :value, gc_stat}, []},
    {vm_io, {:function, Metricman, :io, [], :value, io_stat}, []},
    {vm_processor, {:function, :erlang, :system_info, [:'$dp'], :value, processor_stat}, []},
    {vm_ports, {:function, :erlang, :system_info, [:'$dp'], :value, ports_stat}, []},
    {vm_uptime, {:function, Metricman, :update_uptime, [], :proplist, uptime_stat}, []},
    {vm_statistics, {:function, :erlang, :statistics, [:'$dp'], :value, beam_stat}, []}

  ],

  report: [
    reporters: [
      exometer_report_influxdb: [
        protocol: :http,
        host: "localhost",
        port: 8086,
        db: "dev"
      ]
    ],
    subscribers: [
      {:exometer_report_influxdb, vm_memory, memory_stats, poll_interval, []},
      {:exometer_report_influxdb, vm_processes, processes_stat, poll_interval, []},
      {:exometer_report_influxdb, vm_scheduler, scheduler_stat, poll_interval, []},
      {:exometer_report_influxdb, vm_gc, gc_stat, poll_interval, []},
      {:exometer_report_influxdb, vm_io, io_stat, poll_interval, []},
      {:exometer_report_influxdb, vm_processor, processor_stat, poll_interval, []},
      {:exometer_report_influxdb, vm_ports, ports_stat, poll_interval, []},
      {:exometer_report_influxdb, vm_uptime, uptime_stat, poll_interval, []},
      {:exometer_report_influxdb, vm_statistics, beam_stat, poll_interval, []}

    ]
  ]

config :elixometer,
  reporter: :exometer_report_influxdb,
  update_frequency: 2_000,
  env: Mix.env,
  metric_prefix: "dev_api",
  subscribe_options: [{:tag, []}]
```
NOTE: I am using phoenix `1.2` 
With the above conf when I run my app the memory size of the influx reporter keeps growing. The growth is not visible immediately but over a longer period of time (~3-4 days).

**Comment by surik** [comment] 2017-05-04 08:14
@kansi I've tried to create a test application with your configuration example, see https://github.com/surik/exo_test

You probably see something like 
```
10:14:46.701 [error] InfluxDB reporter HTTP sending error: {:error, :timeout}
```
when memory is grown, right?

**Comment by surik** [comment] 2017-05-08 07:26
I was not able to reproduce the issue with my test application and InfluxDB 1.2.3. 
But once I got the same error as in the description with older InfluxDB (0.13). It looked like InfluxDB was not answering to write requests from the reporter and this error initiated a cycled reconnect on reported side.

**Comment by kansi** [comment] 2017-05-08 09:44
Ok, I will try to find a better way to replicate this (if I can). Thanks for your prompt help.

**Comment by surik** [comment] 2017-10-18 09:11
Hi @kansi, 

I close it for now if you still have the issue feel free to reopen it.

**Closed as completed by surik** 2017-10-18 09:11 UTC
